import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { SignIn, useAuth, UserButton } from '@clerk/nextjs'
import Redirect from '@/components/Redirect'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const { getToken, isLoaded, isSignedIn } = useAuth()
  
  if (isSignedIn) {
    // You can handle the loading or signed state separately
    return <Redirect location='/todos'></Redirect>
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h2>Welcome to Jarod&apos;s Todo App</h2>
        <SignIn redirectUrl='/todos'></SignIn>
        <UserButton></UserButton>
      </main>
    </>
  )
}
